# Copyright (c) 2022-2024 Nicolas ROBERT.
# Distributed under MIT license. Please see LICENSE for details.
package ifneeded ticklecharts 3.2.5 [list apply {dir {

    source [file join $dir ticklecharts.tcl]
    source [file join $dir utils.tcl]
    source [file join $dir chart.tcl]
    source [file join $dir chart3D.tcl]
    source [file join $dir ehuddle.tcl]
    source [file join $dir huddle_patch.tcl]
    source [file join $dir eformat.tcl]
    source [file join $dir jsfunc.tcl]
    source [file join $dir layout.tcl]
    source [file join $dir global_options.tcl]
    source [file join $dir global_options3D.tcl]
    source [file join $dir series.tcl]
    source [file join $dir series3D.tcl]
    source [file join $dir options.tcl]
    source [file join $dir options3D.tcl]
    source [file join $dir axis.tcl]
    source [file join $dir axis3D.tcl]
    source [file join $dir theme.tcl]
    source [file join $dir dataset.tcl]
    source [file join $dir timeline.tcl]
    source [file join $dir etypes.tcl]
    source [file join $dir ecolor.tcl]
    source [file join $dir etrace.tcl]
    source [file join $dir etsb.tcl]
    source [file join $dir ejupyter.tcl]
    source [file join $dir esnap.tcl]

}} $dir]